options:
  region:
    type: string
    default: RegionOne
    description: OpenStack Region
  config-flags:
    type: string
    default:
    description: |
      Comma-separated list of key=value config flags. These values will be
      placed in the masakarimonitors.conf [DEFAULT] section.
